package ai.csap.example.security;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.SignatureAlgorithm;
import io.jsonwebtoken.io.Decoders;
import io.jsonwebtoken.security.Keys;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Service;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import java.util.List;
import java.util.Optional;

/**
 * Issue and verify HS256 JWTs for the demo security layer.
 *
 * <p>Activated only when {@code csap.example.security.enabled=true}.
 */
@Service
@ConditionalOnProperty(prefix = "csap.example.security", name = "enabled", havingValue = "true")
public class JwtService {

    private static final Logger log = LoggerFactory.getLogger(JwtService.class);
    private static final String CLAIM_ROLES = "roles";

    private final SecurityProperties props;
    private final SecretKey signingKey;

    public JwtService(SecurityProperties props) {
        this.props = props;
        this.signingKey = resolveSigningKey(props.getJwtSecret());
    }

    /**
     * Resolve a {@link SecretKey} suitable for HS256. Accepts either:
     *   - a base64-encoded value (preferred when generated by {@code openssl rand -base64 32})
     *   - or a raw UTF-8 string of at least 32 bytes
     */
    private static SecretKey resolveSigningKey(String secret) {
        if (secret == null || secret.isBlank()) {
            throw new IllegalStateException(
                    "csap.example.security.jwt-secret must be configured");
        }
        try {
            byte[] decoded = Decoders.BASE64.decode(secret);
            if (decoded.length >= 32) return Keys.hmacShaKeyFor(decoded);
        } catch (RuntimeException ignored) {
            // not base64 — fall through to raw bytes
        }
        byte[] raw = secret.getBytes(StandardCharsets.UTF_8);
        if (raw.length < 32) {
            throw new IllegalStateException(
                    "csap.example.security.jwt-secret must be at least 32 bytes (HS256)");
        }
        return Keys.hmacShaKeyFor(raw);
    }

    public IssuedToken issueToken(String username, List<String> roles) {
        Instant now = Instant.now();
        Instant exp = now.plus(props.getJwtExpirationMinutes(), ChronoUnit.MINUTES);

        String token = Jwts.builder()
                .issuer(props.getIssuer())
                .subject(username)
                .issuedAt(Date.from(now))
                .expiration(Date.from(exp))
                .claim(CLAIM_ROLES, roles == null ? List.of() : roles)
                .signWith(signingKey, Jwts.SIG.HS256)
                .compact();

        return new IssuedToken(token, exp);
    }

    public Optional<ParsedToken> parseToken(String token) {
        if (token == null || token.isBlank()) return Optional.empty();
        try {
            Claims claims = Jwts.parser()
                    .verifyWith(signingKey)
                    .build()
                    .parseSignedClaims(token)
                    .getPayload();

            @SuppressWarnings("unchecked")
            List<String> roles = (List<String>) claims.getOrDefault(CLAIM_ROLES, List.of());
            return Optional.of(new ParsedToken(claims.getSubject(), roles, claims.getExpiration()));
        } catch (RuntimeException ex) {
            log.debug("JWT verification failed: {}", ex.getMessage());
            return Optional.empty();
        }
    }

    public record IssuedToken(String token, Instant expiresAt) {}

    public record ParsedToken(String username, List<String> roles, Date expiresAt) {}
}
